# Generated by Django 6.0.1 on 2026-06-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityextensionservices', '0003_masterdatadepartment_membercontributionstatement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterDataDepartment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectexpense',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectallocation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectallocation',
            name='allocated_by',
        ),
        migrations.RemoveField(
            model_name='projectallocation',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='projectexpense',
            name='recorded_by',
        ),
        migrations.DeleteModel(
            name='MemberContributionStatement',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectAllocation',
        ),
        migrations.DeleteModel(
            name='ProjectExpense',
        ),
    ]
