# Generated by Django 6.0.1 on 2026-02-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='accession_number',
            field=models.CharField(blank=True, help_text='Unique identifier for the book copy', max_length=50, null=True, unique=True),
        ),
    ]
