# Generated by Django 6.0.1 on 2026-02-06 07:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='library',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='publisher',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('library_name', models.CharField(max_length=200)),
                ('default_loan_period_days', models.IntegerField(default=14, help_text='Default loan period in days')),
                ('maximum_renewals', models.IntegerField(default=2)),
                ('maximum_books_per_user', models.IntegerField(default=5)),
                ('enable_fines', models.BooleanField(default=True)),
                ('daily_fine_amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('maximum_fine_amount', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('grace_period_days', models.IntegerField(default=0)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
                ('notify_due_dates', models.BooleanField(default=True)),
                ('notify_overdue', models.BooleanField(default=True)),
                ('notify_reservation_ready', models.BooleanField(default=True)),
                ('days_before_due_notification', models.IntegerField(default=3, help_text='Days before due date to send reminder')),
                ('enable_book_recommendations', models.BooleanField(default=True)),
                ('enable_trending_analysis', models.BooleanField(default=True)),
                ('enable_user_analytics', models.BooleanField(default=True)),
                ('enable_digital_resources', models.BooleanField(default=True)),
                ('reservation_expiry_days', models.IntegerField(default=3, help_text='Days until reservation expires after ready')),
                ('auto_extend_on_no_reservation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='librarymanagement.library')),
            ],
            options={
                'verbose_name_plural': 'Library Settings',
            },
        ),
    ]
