# Generated by Django 6.0.1 on 2026-03-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanagement', '0003_mlinsight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLInsight',
        ),
    ]
