# Generated by Django 6.0.1 on 2026-01-23 01:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('core', 'Core'), ('projectmanagement', 'Project Management'), ('librarymanagement', 'Library Management'), ('inventorymanagement', 'Inventory Management'), ('communityextensionservices', 'Community Extension Services'), ('informationmanagement', 'Information Management'), ('performanceevaluation', 'Performance Evaluation')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('terms_of_service', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True)),
                ('_phone_number', models.CharField(blank=True, db_column='phone_number', max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping'), ('home', 'Home')], max_length=20)),
                ('full_address_encrypted', models.TextField()),
                ('city_encrypted', models.TextField(blank=True)),
                ('province_encrypted', models.TextField(blank=True)),
                ('postal_code_encrypted', models.TextField(blank=True)),
                ('country_encrypted', models.TextField(blank=True)),
                ('phone_encrypted', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'addresses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('system_name', models.CharField(choices=[('core', 'Core'), ('projectmanagement', 'Project Management'), ('librarymanagement', 'Library Management'), ('inventorymanagement', 'Inventory Management'), ('communityextensionservices', 'Community Extension Services'), ('informationmanagement', 'Information Management'), ('performanceevaluation', 'Performance Evaluation')], default='core', max_length=50)),
                ('target_model', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(choices=[('core', 'Core'), ('projectmanagement', 'Project Management'), ('librarymanagement', 'Library Management'), ('inventorymanagement', 'Inventory Management'), ('communityextensionservices', 'Community Extension Services'), ('informationmanagement', 'Information Management'), ('performanceevaluation', 'Performance Evaluation')], default='core', max_length=50)),
                ('system_role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User'), ('superadmin', 'Super Admin')], max_length=50, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'system_name')},
            },
        ),
    ]
