# Generated by Django 6.0.1 on 2026-02-02 12:22

from django.db import migrations


def seed_systems_and_memberships(apps, schema_editor):
    Systems = apps.get_model('core', 'Systems')
    SystemMembership = apps.get_model('core', 'SystemMembership')
    CustomUser = apps.get_model('core', 'CustomUser')
    
    # Define all systems
    systems_data = [
        ('core', 'Core System', 'Core system for user management and authentication.'),
        ('projectmanagement', 'Project Management', 'Manage projects, tasks, and team collaboration.'),
        ('librarymanagement', 'Library Management', 'Manage library resources, books, and borrowing.'),
        ('inventorymanagement', 'Inventory Management', 'Track and manage inventory items and stock.'),
        ('communityextensionservices', 'Community Extension Services', 'Manage community outreach and extension programs.'),
        ('informationmanagement', 'Information Management', 'Centralized information and document management.'),
        ('performanceevaluation', 'Performance Evaluation', 'Evaluate and track employee performance.'),
        ('scholarshipmanagement', 'Scholarship Management', 'Manage and administer scholarship programs and applications.'),
    ]
    
    # Create Systems entries
    for system_name, display_name, description in systems_data:
        Systems.objects.get_or_create(
            name=system_name,
            defaults={
                'description': description,
                'terms_of_service': f'Terms of Service for {display_name}. Please review and accept to use this system.'
            }
        )
    
    # Add system memberships for admin user
    try:
        admin_user = CustomUser.objects.get(username='admin')
        
        for system_name, _, _ in systems_data:
            SystemMembership.objects.get_or_create(
                user=admin_user,
                system_name=system_name,
                defaults={
                    'system_role': 'superadmin'
                }
            )
    except CustomUser.DoesNotExist:
        pass  # Admin user doesn't exist yet, skip membership creation


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_systems_and_memberships, reverse_code=migrations.RunPython.noop),
    ]
