# Generated by Django 6.0.1 on 2026-01-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_systems'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='hidden_description',
            field=models.TextField(blank=True),
        ),
    ]
