# Generated by Django 6.0.1 on 2026-03-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='system_name',
            field=models.CharField(choices=[('core', 'Core'), ('projectmanagement', 'Research Management'), ('librarymanagement', 'Library Management'), ('inventorymanagement', 'Inventory Management'), ('communityextensionservices', 'Community Extension Services'), ('informationmanagement', 'Information Management'), ('performanceevaluation', 'Performance Evaluation')], default='core', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemmembership',
            name='system_name',
            field=models.CharField(choices=[('core', 'Core'), ('projectmanagement', 'Research Management'), ('librarymanagement', 'Library Management'), ('inventorymanagement', 'Inventory Management'), ('communityextensionservices', 'Community Extension Services'), ('informationmanagement', 'Information Management'), ('performanceevaluation', 'Performance Evaluation')], default='core', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemmembership',
            name='system_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('researcher', 'Researcher'), ('user', 'User'), ('instructor', 'Instructor'), ('superadmin', 'Super Admin')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systems',
            name='name',
            field=models.CharField(choices=[('core', 'Core'), ('projectmanagement', 'Research Management'), ('librarymanagement', 'Library Management'), ('inventorymanagement', 'Inventory Management'), ('communityextensionservices', 'Community Extension Services'), ('informationmanagement', 'Information Management'), ('performanceevaluation', 'Performance Evaluation')], max_length=50, unique=True),
        ),
    ]
