# Generated by Django 6.0.1 on 2026-03-17 13:53

from django.db import migrations, models


def rename_system_forward(apps, schema_editor):
    for model_name in ('Systems', 'SystemMembership', 'Logs'):
        Model = apps.get_model('core', model_name)
        field = 'name' if model_name == 'Systems' else 'system_name'
        Model.objects.filter(**{field: 'projectmanagement'}).update(**{field: 'researchmanagement'})


def rename_system_backward(apps, schema_editor):
    for model_name in ('Systems', 'SystemMembership', 'Logs'):
        Model = apps.get_model('core', model_name)
        field = 'name' if model_name == 'Systems' else 'system_name'
        Model.objects.filter(**{field: 'researchmanagement'}).update(**{field: 'projectmanagement'})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_logs_system_name_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_system_forward, rename_system_backward),
        migrations.AlterField(
            model_name='logs',
            name='system_name',
            field=models.CharField(choices=[('core', 'Core'), ('researchmanagement', 'Research Management'), ('librarymanagement', 'Library Management'), ('inventorymanagement', 'Inventory Management'), ('communityextensionservices', 'Community Extension Services'), ('informationmanagement', 'Information Management'), ('performanceevaluation', 'Performance Evaluation')], default='core', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemmembership',
            name='system_name',
            field=models.CharField(choices=[('core', 'Core'), ('researchmanagement', 'Research Management'), ('librarymanagement', 'Library Management'), ('inventorymanagement', 'Inventory Management'), ('communityextensionservices', 'Community Extension Services'), ('informationmanagement', 'Information Management'), ('performanceevaluation', 'Performance Evaluation')], default='core', max_length=50),
        ),
        migrations.AlterField(
            model_name='systems',
            name='name',
            field=models.CharField(choices=[('core', 'Core'), ('researchmanagement', 'Research Management'), ('librarymanagement', 'Library Management'), ('inventorymanagement', 'Inventory Management'), ('communityextensionservices', 'Community Extension Services'), ('informationmanagement', 'Information Management'), ('performanceevaluation', 'Performance Evaluation')], max_length=50, unique=True),
        ),
    ]
