# Generated by Django 6.0.1 on 2026-06-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_projectmanagement_to_researchmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='system_name',
            field=models.CharField(choices=[('core', 'Core'), ('researchmanagement', 'Research Management'), ('librarymanagement', 'Library Management'), ('inventorymanagement', 'Inventory Management'), ('communityextensionservices', 'Community Extension Services'), ('informationmanagement', 'Information Management'), ('performanceevaluation', 'Performance Evaluation'), ('scholarshipmanagement', 'Scholarship Management')], default='core', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemmembership',
            name='system_name',
            field=models.CharField(choices=[('core', 'Core'), ('researchmanagement', 'Research Management'), ('librarymanagement', 'Library Management'), ('inventorymanagement', 'Inventory Management'), ('communityextensionservices', 'Community Extension Services'), ('informationmanagement', 'Information Management'), ('performanceevaluation', 'Performance Evaluation'), ('scholarshipmanagement', 'Scholarship Management')], default='core', max_length=50),
        ),
        migrations.AlterField(
            model_name='systems',
            name='name',
            field=models.CharField(choices=[('core', 'Core'), ('researchmanagement', 'Research Management'), ('librarymanagement', 'Library Management'), ('inventorymanagement', 'Inventory Management'), ('communityextensionservices', 'Community Extension Services'), ('informationmanagement', 'Information Management'), ('performanceevaluation', 'Performance Evaluation'), ('scholarshipmanagement', 'Scholarship Management')], max_length=50, unique=True),
        ),
    ]
