# Generated by Django 6.0.1 on 2026-01-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='full_address2',
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
