# Generated by Django 6.0.1 on 2026-06-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_systemmembership_system_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmembership',
            name='system_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('researcher', 'Researcher'), ('user', 'User'), ('instructor', 'Instructor'), ('superadmin', 'Super Admin'), ('reviewer', 'Reviewer'), ('student', 'Student')], max_length=50, null=True),
        ),
    ]
