# Generated by Django 6.0.1 on 2026-01-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='full_address',
            new_name='full_address_encrypted',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
        migrations.AddField(
            model_name='address',
            name='city_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='address',
            name='province_encrypted',
            field=models.TextField(blank=True),
        ),
    ]
