# Generated by Django 6.0.1 on 2026-01-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='_phone_number',
            field=models.CharField(blank=True, db_column='phone_number', max_length=255),
        ),
    ]
