# Generated by Django 6.0.1 on 2026-01-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customuser_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
