# Generated by Django 6.0.1 on 2026-01-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_customuser_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoreAccess',
        ),
    ]
