# Generated by Django 6.0.1 on 2026-01-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_systemmembership'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminLog',
            new_name='Logs',
        ),
    ]
