# Generated by Django 6.0.1 on 2026-01-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_adminlog_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='system_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
