# Generated by Django 6.0.1 on 2026-01-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customuser_system_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='system_role',
        ),
        migrations.AddField(
            model_name='systemmembership',
            name='system_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
