# Generated by Django 6.0.1 on 2026-02-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('participants', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BeneficiaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('segment', models.CharField(max_length=120)),
                ('households', models.PositiveIntegerField(default=0)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MLExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed'), ('Queued', 'Queued')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Prototype', 'Prototype'), ('Training', 'Training'), ('Ready', 'Ready')], max_length=20)),
                ('metric', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='MLPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Design', 'Design'), ('Operational', 'Operational')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('partner_type', models.CharField(choices=[('Government', 'Government'), ('NGO', 'NGO'), ('Private', 'Private'), ('Academe', 'Academe')], max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Prospecting', 'Prospecting'), ('Dormant', 'Dormant')], max_length=20)),
                ('engagement', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('contribution', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Livelihood', 'Livelihood'), ('Environment', 'Environment'), ('Governance', 'Governance')], max_length=50)),
                ('lead', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Proposed', 'Proposed'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('beneficiaries_count', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('predicted_success', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('predicted_reach', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('In Review', 'In Review'), ('Generated', 'Generated')], max_length=20)),
                ('owner', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
