# Generated by Django 6.0.1 on 2026-06-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationmanagement', '0003_add_contribution_financial_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionfund',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution_funds', to='informationmanagement.project'),
        ),
        migrations.AddField(
            model_name='membercontributionrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_contributions', to='informationmanagement.project'),
        ),
        migrations.AlterField(
            model_name='membercontributionrecord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_records', to='informationmanagement.masterdatadepartment'),
        ),
    ]
