# Generated by Django 6.0.1 on 2026-06-29 16:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityextensionservices', '0004_delete_masterdatadepartment_and_more'),
        ('informationmanagement', '0004_add_project_relationships'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Association Fund', max_length=200)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='contribution_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='beneficiary_groups',
            field=models.ManyToManyField(blank=True, related_name='projects', to='informationmanagement.beneficiarygroup'),
        ),
        migrations.AddField(
            model_name='project',
            name='member_selection_mode',
            field=models.CharField(choices=[('manual', 'Select Members Manually'), ('all_members', 'ALL Members')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='selected_members',
            field=models.ManyToManyField(blank=True, related_name='information_projects', to='communityextensionservices.member'),
        ),
        migrations.AlterField(
            model_name='contributionfund',
            name='budget_required',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='AssociationFundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('member_contribution', 'Member Contribution'), ('partner_contribution', 'Partner Contribution'), ('other_income', 'Other Income'), ('expense', 'Expense')], max_length=30)),
                ('source_type', models.CharField(choices=[('member_contribution', 'Member Contribution'), ('partner_contribution', 'Partner Contribution'), ('other_income', 'Other Income'), ('expense', 'Expense')], default='other_income', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_model', models.CharField(blank=True, max_length=80)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('association_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='informationmanagement.associationfund')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberContributionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='informationmanagement.membercontributionrecord')),
            ],
            options={
                'ordering': ['-contribution_date', '-created_at'],
            },
        ),
    ]
