# Generated by Django 6.0.1 on 2026-07-21 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationmanagement', '0005_associationfund_partner_contribution_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionSupportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Decision Support Summary', max_length=200)),
                ('content', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(blank=True, max_length=120)),
                ('report_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='informationmanagement.reporttemplate'),
        ),
    ]
