# Generated by Django 6.0.1 on 2026-06-18 14:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined')], default='draft', max_length=20)),
                ('motivation_essay', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('review', 'Review'), ('decide', 'Decision'), ('contact', 'Contact')], max_length=20)),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.UUIDField()),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('government_id', 'Government-Issued ID'), ('transcript', 'Transcript / Report Card'), ('income_proof', 'Income Proof'), ('recommendation_letter', 'Recommendation Letter'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='scholarship_documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('academic_score', models.FloatField(blank=True, help_text='Academic performance (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('financial_need_score', models.FloatField(blank=True, help_text='Financial need assessment (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('interview_score', models.FloatField(blank=True, help_text='Interview score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('extracurricular_score', models.FloatField(blank=True, help_text='Extracurricular activities (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('total_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('recommendation', models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject'), ('waitlist', 'Waitlist')], max_length=20, null=True)),
                ('reviewer_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='scholarshipmanagement.application')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_conducted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RejectionAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qualification_status', models.BooleanField(default=False)),
                ('rejected_category', models.CharField(choices=[('academic', 'Academic'), ('financial', 'Financial'), ('document', 'Document'), ('quota', 'Quota'), ('other', 'Other')], max_length=20)),
                ('failed_criteria', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('analysis_summary', models.TextField(blank=True)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_analysis', to='scholarshipmanagement.application')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('merit_based', 'Merit-Based'), ('need_based', 'Need-Based'), ('talent_based', 'Talent-Based')], max_length=20)),
                ('scholarship_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('corporate', 'Corporate'), ('organization', 'Organization')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('award_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('number_of_slots', models.PositiveIntegerField()),
                ('renewable', models.BooleanField(default=False)),
                ('eligibility_rules', models.JSONField(blank=True, default=dict)),
                ('required_documents', models.JSONField(blank=True, default=list, help_text="Array of required document types: ['government_id', 'transcript', 'income_proof']")),
                ('application_start_date', models.DateTimeField()),
                ('application_end_date', models.DateTimeField()),
                ('decision_announcement_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_scholarships', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scholarships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('stage_unlocked', 'Stage Unlocked'), ('application_status', 'Application Status Update'), ('decision_released', 'Decision Released'), ('deadline_reminder', 'Deadline Reminder'), ('document_verified', 'Document Verified'), ('offer_received', 'Scholarship Offer'), ('system_update', 'System Update')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scholarshipmanagement.application')),
                ('related_scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scholarshipmanagement.scholarship')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarshipmanagement.scholarship'),
        ),
        migrations.CreateModel(
            name='ScholarshipOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Student Response'), ('accepted', 'Accepted by Student'), ('declined', 'Declined by Student'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='scholarship_offers/%Y/%m/%d/')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='scholarshipmanagement.application')),
            ],
        ),
        migrations.CreateModel(
            name='RenewalApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('renewal_year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('conditional', 'Conditional'), ('terminated', 'Terminated')], default='submitted', max_length=20)),
                ('updated_grades', models.FileField(blank=True, null=True, upload_to='renewal_documents/%Y/%m/%d/')),
                ('progress_report', models.TextField(blank=True)),
                ('behavioral_evaluation', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('renewal_decision_date', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='scholarshipmanagement.scholarshipoffer')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_1_status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=20)),
                ('stage_1_completed_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('family_background', models.TextField(blank=True)),
                ('school_university', models.CharField(blank=True, max_length=255)),
                ('course_strand', models.CharField(blank=True, max_length=255)),
                ('gpa', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('academic_awards', models.TextField(blank=True)),
                ('annual_family_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('financial_need_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('province', models.CharField(blank=True, max_length=100)),
                ('location_coords', models.CharField(blank=True, max_length=100)),
                ('all_required_fields_filled', models.BooleanField(default=False)),
                ('all_required_documents_uploaded', models.BooleanField(default=False)),
                ('validation_checks_passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('access_scholarship_management_system', 'Can access Scholarship Management system'), ('view_student_dashboard', 'Can view student dashboard'), ('manage_scholarship_applications', 'Can manage scholarship applications')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'scholarship')},
        ),
        migrations.CreateModel(
            name='RecommendationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('eligibility_probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('success_probability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reason_tags', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_recommendations', to='scholarshipmanagement.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='scholarshipmanagement.studentprofile')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('student', 'scholarship')},
            },
        ),
    ]
