# Generated by Django 6.0.1 on 2026-07-09 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='attendance_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='failed_subjects',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='socioeconomic_status',
            field=models.CharField(choices=[('low', 'Low'), ('middle', 'Middle'), ('high', 'High')], default='middle', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='units_enrolled',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
