# Generated by Django 6.0.1 on 2026-07-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanagement', '0002_mlinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='borrower_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='borrower_contact_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='requisition',
            name='borrower_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='requisition',
            name='borrower_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='requisition',
            name='borrower_middle_initial',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='requisition',
            name='borrower_position',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='requisition',
            name='date_borrowed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='event_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='requisition',
            name='time_borrowed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='time_returned',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
