# Generated by Django 6.0.1 on 2026-01-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0002_task_assigned_team_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='core.CustomUser'),
        ),
    ]
