# Generated by Django 6.0.1 on 2026-03-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0002_mlinsight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('access_project_management_system', 'Can access Research Management system')]},
        ),
        migrations.AddField(
            model_name='project',
            name='auto_detected_topic',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='publication_scope',
            field=models.CharField(choices=[('local', 'Local'), ('international', 'International')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('for_publication', 'For Publication'), ('published', 'Published')], default='draft', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='repository_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='research_method',
            field=models.CharField(choices=[('action_research', 'Action Research'), ('text_mining', 'Text Mining'), ('case_study', 'Case Study'), ('experimental', 'Experimental'), ('mixed_methods', 'Mixed Methods'), ('other', 'Other')], default='action_research', max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='source_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='text_mining_summary',
            field=models.TextField(blank=True),
        ),
    ]
