# Generated by Django 6.0.1 on 2026-01-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0005_team_created_at_team_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
    ]
