# Generated by Django 6.0.1 on 2026-02-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performanceevaluation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
