# Generated by Django 6.0.1 on 2026-03-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceevaluation', '0002_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('target', models.CharField(max_length=120)),
                ('algorithm', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('training', 'Training'), ('ready', 'Ready')], default='draft', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
